version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
       - aws s3 cp --recursive --acl public-read ./dist s3://$bucket_name/ 
       - aws cloudfront create-invalidation --distribution-id $dist_id --paths '/*'

artifacts:
  files:
    - '**/*'
  base-directory: dist
